In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.10.0.dev20251010+cu128


In [3]:
vector = torch.tensor([7,7])

### Random tensors 

why random tensors?

most NNs start with tensors with random numbers drawn from a distribution and then learn and adjust those numbers to better fit the data.

its a loop

###

In [7]:
#random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.5794, 0.0201, 0.3405, 0.8860],
        [0.6348, 0.5335, 0.2561, 0.4840],
        [0.3195, 0.1726, 0.6370, 0.8925]])

In [10]:
binary_tensor = (random_tensor >= 0.114).int()

binary_tensor

tensor([[1, 0, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)

In [12]:
zeros = torch.zeros(size=(3,4))

In [14]:
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [15]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [16]:
ones.dtype

torch.float32

In [18]:
torch.arange(4,10,2)

tensor([4, 6, 8])

In [21]:
 #move the tensor to GPU
s = torch.tensor([3,6,5], device="cuda")

In [22]:
s.dtype

torch.int64

In [25]:
s.size()

torch.Size([3])

In [26]:
s.shape

torch.Size([3])

In [27]:
s.device

device(type='cuda', index=0)

In [28]:
### manipulation of tensors ( tensor operations )

# ADD
t = torch.tensor([1,2,3])
t + 10

tensor([11, 12, 13])

In [30]:
t * 10

tensor([10, 20, 30])

In [31]:
t * t # hadamard product of the 2 tensor vectors

tensor([1, 4, 9])

In [33]:
torch.matmul(t, t) #dot product of the 2 tensor vectors

tensor(14)

In [35]:
t @ t # short hand for the dot product or matrix multiplication

tensor(14)

In [37]:
torch.rand(3,2) @ torch.rand(2,3)

tensor([[0.3090, 0.3713, 0.3270],
        [0.4033, 0.5022, 0.4677],
        [0.8607, 0.9558, 0.7299]])

In [39]:
torch.matmul( torch.rand(3,2), torch.rand(2,3) )

tensor([[0.6242, 0.3181, 0.6975],
        [0.7849, 0.5716, 0.4748],
        [0.5637, 0.3016, 0.5962]])

In [42]:
t_A = torch.tensor( [[1,2], 
                     [3,4],
                     [5,6]] )
t_B = torch.tensor( [[1,2,5], 
                     [3,4,6]] )

torch.mm(t_A, t_B) #torch.matmul = torch.mm

tensor([[ 7, 10, 17],
        [15, 22, 39],
        [23, 34, 61]])

In [43]:
t_A.T

tensor([[1, 3, 5],
        [2, 4, 6]])

In [44]:
x = torch.arange(0, 100, 10)

In [46]:
torch.min(x)

tensor(0)

In [52]:
x.min()

TypeError: Tensor.index() missing 2 required positional arguments: 'positions' and 'dims'

In [50]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [51]:
x.type(torch.float32).mean()

tensor(45.)

In [58]:
x.argmax().item()

9

In [59]:
x.max().item()

90

In [61]:
x.sum().item()

450

In [62]:
x = torch.arange(1., 10.)

In [63]:
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [64]:
x.shape

torch.Size([9])

In [68]:
x_reshaped = x.reshape(3, 3)
x_reshaped

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [69]:
z = x.view(1, 9)
z

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [70]:
#a view of tensor shares the same memory as the original input
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [75]:
x_stacked = torch.stack([x,x,x,x], dim = 1)

In [76]:
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])